source "https://rubygems.org"
  gem "os"
  gem "vmstat"
  gem "nokogiri"
  gem "webrobots"
  gem "celluloid"
  # gem "excon"
  gem "typhoeus"
  gem "datamapper"
  gem "dm-sqlite-adapter"

  gem "sinatra"
  gem "slim"
  gem "sass"